stages:
  cleaning:
    cmd: python -m src.pipeline_cleaning data/raw/ltv_base.csv data/final/ltv_base_final.csv
    deps:
      - data/raw/ltv_base.csv
      - src/pipeline_cleaning.py
      - src/data_loader.py
    outs:
      - data/final/ltv_base_final.csv
  train:
    cmd: python -m src.pipeline_train data/final/ltv_base_final.csv
    deps:
      - data/final/ltv_base_final.csv
      - src/pipeline_train.py
      - src/models.py
